import { palette } from "./palette";

/**
 * 시맨틱 컬러 토큰. 컴포넌트는 이 키에서 생성된 CSS 변수만 사용한다.
 * light와 dark는 반드시 동일한 키 세트를 가진다 (buildCss.test.ts에서 강제).
 *
 * 다크는 단순 반전이 아니라 채도/명도 재조정:
 * - 브랜드/상태 컬러는 한 단계 밝은 스텝 (blue 500 → 400)
 * - 틴트 배경은 어두운 900 스텝
 * - 층위(elevation)는 그림자 대신 표면 밝기 차이 (surface 200 → 250 → 300)
 */
export const themes = {
  light: {
    "color.background.default": palette.gray[0],
    "color.background.surface": palette.gray[0],
    "color.background.surface-raised": palette.gray[0],
    "color.background.surface-overlay": palette.gray[0],
    "color.background.subtle": palette.gray[50],
    "color.background.brand": palette.blue[500],
    "color.background.brand-hovered": palette.blue[600],
    "color.background.brand-pressed": palette.blue[700],
    "color.background.brand-subtle": palette.blue[50],
    "color.background.selected": palette.blue[50],
    "color.background.neutral": palette.gray[100],
    "color.background.neutral-hovered": palette.gray[200],
    "color.background.neutral-pressed": palette.gray[300],
    "color.background.danger": palette.red[500],
    "color.background.danger-hovered": palette.red[600],
    "color.background.danger-pressed": palette.red[700],
    "color.background.success": palette.green[500],
    "color.background.warning": palette.orange[400],
    "color.background.info": palette.teal[500],
    "color.background.brand-subtle-hovered": palette.blue[100],
    "color.background.success-subtle": palette.green[100],
    "color.background.warning-subtle": palette.orange[100],
    "color.background.danger-subtle": palette.red[100],
    "color.background.info-subtle": palette.teal[100],
    "color.background.input": palette.gray[0],
    "color.background.disabled": palette.gray[100],
    "color.background.inverse": palette.gray[800],
    "color.blanket": "rgba(9, 14, 22, 0.55)",
    "color.text.default": palette.gray[900],
    "color.text.subtle": palette.gray[500],
    "color.text.disabled": palette.gray[400],
    "color.text.inverse": palette.gray[0],
    "color.text.brand": palette.blue[600],
    "color.text.success": palette.green[600],
    "color.text.warning": palette.orange[600],
    "color.text.danger": palette.red[600],
    "color.text.info": palette.teal[600],
    "color.text.link": palette.blue[600],
    "color.text.link-hovered": palette.blue[700],
    "color.text.selected": palette.blue[600],
    "color.border.default": palette.gray[200],
    "color.border.input": palette.gray[300],
    "color.border.focused": palette.blue[500],
    "color.border.brand": palette.blue[500],
    "color.border.danger": palette.red[500],
    "color.border.disabled": palette.gray[100],
    "shadow.100": "0 1px 2px rgba(20, 27, 37, 0.10), 0 0 1px rgba(20, 27, 37, 0.14)",
    "shadow.200": "0 4px 10px rgba(20, 27, 37, 0.14), 0 0 1px rgba(20, 27, 37, 0.10)",
    "shadow.300": "0 12px 28px rgba(20, 27, 37, 0.20), 0 0 1px rgba(20, 27, 37, 0.10)",
    "shadow.overlay": "0 12px 28px rgba(20, 27, 37, 0.20), 0 0 1px rgba(20, 27, 37, 0.10)",
  },
  dark: {
    "color.background.default": palette.darkGray[100],
    "color.background.surface": palette.darkGray[200],
    "color.background.surface-raised": palette.darkGray[250],
    "color.background.surface-overlay": palette.darkGray[300],
    "color.background.subtle": palette.darkGray[0],
    "color.background.brand": palette.blue[400],
    "color.background.brand-hovered": palette.blue[300],
    "color.background.brand-pressed": palette.blue[200],
    "color.background.brand-subtle": palette.blue[900],
    "color.background.selected": palette.blue[800],
    "color.background.neutral": palette.darkGray[250],
    "color.background.neutral-hovered": palette.darkGray[300],
    "color.background.neutral-pressed": palette.darkGray[350],
    "color.background.danger": palette.red[400],
    "color.background.danger-hovered": palette.red[300],
    "color.background.danger-pressed": palette.red[200],
    "color.background.success": palette.green[400],
    "color.background.warning": palette.orange[400],
    "color.background.info": palette.teal[400],
    "color.background.brand-subtle-hovered": palette.blue[800],
    "color.background.success-subtle": palette.green[900],
    "color.background.warning-subtle": palette.orange[900],
    "color.background.danger-subtle": palette.red[900],
    "color.background.info-subtle": palette.teal[900],
    "color.background.input": palette.darkGray[200],
    "color.background.disabled": palette.darkGray[250],
    "color.background.inverse": palette.darkGray[1000],
    "color.blanket": "rgba(3, 5, 9, 0.65)",
    "color.text.default": palette.darkGray[1000],
    "color.text.subtle": palette.darkGray[800],
    "color.text.disabled": palette.darkGray[500],
    "color.text.inverse": palette.darkGray[100],
    "color.text.brand": palette.blue[300],
    "color.text.success": palette.green[400],
    "color.text.warning": palette.orange[300],
    "color.text.danger": palette.red[400],
    "color.text.info": palette.teal[400],
    "color.text.link": palette.blue[300],
    "color.text.link-hovered": palette.blue[200],
    "color.text.selected": palette.blue[200],
    "color.border.default": palette.darkGray[350],
    "color.border.input": palette.darkGray[400],
    "color.border.focused": palette.blue[300],
    "color.border.brand": palette.blue[300],
    "color.border.danger": palette.red[400],
    "color.border.disabled": palette.darkGray[250],
    "shadow.100": "0 0 0 1px rgba(255, 255, 255, 0.06)",
    "shadow.200": "0 0 0 1px rgba(255, 255, 255, 0.08)",
    "shadow.300": "0 0 0 1px rgba(255, 255, 255, 0.10), 0 8px 24px rgba(0, 0, 0, 0.50)",
    "shadow.overlay": "0 0 0 1px rgba(255, 255, 255, 0.10), 0 8px 24px rgba(0, 0, 0, 0.50)",
  },
} as const;
